#!/bin/bash

set +e
VERSION=
echo "Stopping PHP"

systemctl stop php-fpm-$VERSION.service
systemctl disable php-fpm-$VERSION.service

$(which mkdir -p) /var/run/php/$VERSION
$(which touch) /var/run/php/$VERSION/php-fpm.pid

WWWDATAUSER=$(id www-data)
if [ $? -eq 1 ]; then
    echo "Creating www-data user"
    useradd -Mr www-data
fi

exit 0