---
sudo: required
dist: trusty

language: generic

env:
  - BUILD_IMAGE=bionic
  - BUILD_IMAGE=xenial
  - BUILD_IMAGE=trusty
  - BUILD_IMAGE=centos7
  - BUILD_IMAGE=rhel7
  - BUILD_IMAGE=alpine3.6
  - BUILD_IMAGE=alpine3.7
  - BUILD_IMAGE=alpine3.8

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - mkdir -p build/deb/trusty build/deb/xenial build/deb/bionic build/rpm/CentOS/7/x86_64 build/rpm/RHEL/7/x86_64 build/alpine/v3.6/x86_64 build/alpine/v3.7/x86_64 build/alpine/v3.8/x86_64

script:
  - if [ -n "$TRAVIS_TAG" ]; then export VERSION=$( cut -d '-' -f 1 <<< "$TRAVIS_TAG" ) export RELEASEVER=$( cut -d '-' -f 2 <<< "$TRAVIS_TAG" ); echo "Setting versions via TravisCI Tag"; fi
  - VERSION=$VERSION RELEASEVER=$RELEASEVER docker-compose run $BUILD_IMAGE
  - if [ "$BUILD_IMAGE" == "trusty" ] || [ "$BUILD_IMAGE" == "xenial" ] || [ "$BUILD_IMAGE" == "bionic" ]; then mv *$BUILD_IMAGE*.deb build/deb/$BUILD_IMAGE; fi
  - if [ "$BUILD_IMAGE" == "centos7" ]; then mv *.rpm build/rpm/CentOS/7/x86_64; fi
  - if [ "$BUILD_IMAGE" == "rhel7" ]; then mv *.rpm build/rpm/RHEL/7/x86_64; fi
  - if [ "$BUILD_IMAGE" == "alpine3.6" ]; then mv *.apk build/alpine/v3.6/x86_64; fi
  - if [ "$BUILD_IMAGE" == "alpine3.7" ]; then mv *.apk build/alpine/v3.7/x86_64; fi
  - if [ "$BUILD_IMAGE" == "alpine3.8" ]; then mv *.apk build/alpine/v3.8/x86_64; fi

after_failure:
  - cat /tmp/php-$VERSION/config.log

deploy:
  provider: s3
  access_key_id: AKIAINRCDYGMMTSHTIHA
  secret_access_key:
    secure: 2XQmmT2Lmrui0hh/aCnNnKU37/daK6XWV2OlebDHtePpZJfFVRzI7x88JL7QaPM4wzg6aGkNjchXlHd2UFMDYAdo3CHHGEQNU/uXjlAO7di0Cn5GSeTVPKqaaow2IuMWcZrYm3HJVQZ3rG292owtwgQ/36D05w7GayVUijUtBBnBblqetbKIZBdkQ3J/Vj687uvk1cf1Isjh8+2z51ZmSxJrS/klspOd2oP2QnPWRkD4ElIDCsYtefPhjJDKMJzpWCMB+QOwWYdlip/tUkJ2OPuQ1iLWmkthyRdclB9YWEaDgWz2fsqu2chuDSHZl+GcdLBGnGC9l/nBYjiSvulsGinlAUXQny01T4oejr/B7vPccHh2Q2Y0cjY0GJG5fiHJ89GJkluFhbHV6C6N15u0lkCjxC7WaqFoLFjqVdxVQLE/VlxAS7MCwcY3O02Aj9uRbW/A1evwI0mk553pmYLEMhdFbRUTF8PKjg+tKHMwJtG2rh8u60klw/eFPsWQEliWRsK8ZEfvdGKncaXBraCgBX8Woc7n1xJoqbCrLNQkM/oNS7BHq6udrIUJBRzcNAcvXgopBLN3BGHzdDL4yXZJiRpz9nlF9VHu0F3ZzslYWPoHipXAcIrO3jh+2Vt5AqCoYbLn1+io++AXlNtoec7WohtZB7m/VFCUztvl7NeAyYw=
  bucket: travis-packages.erianna.com
  detect_encoding: true
  skip_cleanup: true
  acl: public_read
  region: us-west-2
  local_dir: build 
  on:
    tags: true
    all_branches: false
    repo: charlesportwoodii/php-fpm-build
