# docker-compose.yml

version: '3'
services:
    xenial:
        image: charlesportwoodii/ubuntu:16.04-build
        container_name: xenial_x64
        command: bash -lc "make build fpm_debian VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - EXTRA_DEB_PACKAGES=http://security.ubuntu.com/ubuntu/pool/universe/libz/libzip/libzip4_1.1.2-1.1_amd64.deb http://launchpadlibrarian.net/260671105/libzip-dev_1.1.2-1.1_amd64.deb
            - EXTRA_APT_PACKAGES=bison libbison-dev
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
    bionic:
        image: charlesportwoodii/ubuntu:18.04-build
        container_name: xenial_x64
        command: bash -lc "make build fpm_debian VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
            - EXTRA_APT_PACKAGES=bison libbison-dev re2c
    centos7:
        image: charlesportwoodii/centos:7-build
        container_name: centos7_x86_64
        command: bash -lc "make build fpm_rpm VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - EXTRA_RPM_PACKAGES=http://rpms.remirepo.net/enterprise/7/remi/x86_64/libzip5-1.5.1-1.el7.remi.x86_64.rpm http://rpms.remirepo.net/enterprise/7/remi/x86_64//libzip5-devel-1.5.1-1.el7.remi.x86_64.rpm
            - REMOVE_RPM_PACKAGES=libzip libzip-devel
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
    rhel7:
        image: charlesportwoodii/rhel:7-build
        container_name: rhel7_x86_64
        command: bash -lc "make build fpm_rpm VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - EXTRA_RPM_PACKAGES=http://rpms.remirepo.net/enterprise/7/remi/x86_64/libzip5-1.5.1-1.el7.remi.x86_64.rpm http://rpms.remirepo.net/enterprise/7/remi/x86_64//libzip5-devel-1.5.1-1.el7.remi.x86_64.rpm
            - REMOVE_RPM_PACKAGES=libzip libzip-devel
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
    alpine3.7:
        image: charlesportwoodii/alpine:3.7-build
        container_name: alpine37_x86_64
        command: bash -lc "apk add --no-cache linux-headers; make build fpm_alpine VERSION=$VERSION RELEASEVER=$RELEASEVER ALPINE_VERSION=$ALPINE_VERSION"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - ALPINE_VERSION=370
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
    alpine3.8:
        image: charlesportwoodii/alpine:3.8-build
        container_name: alpine38_x86_64
        command: bash -lc "apk add --no-cache linux-headers; make build fpm_alpine VERSION=$VERSION RELEASEVER=$RELEASEVER ALPINE_VERSION=$ALPINE_VERSION"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - ALPINE_VERSION=380
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
    alpine3.9:
        image: charlesportwoodii/alpine:3.9-build
        container_name: alpine38_x86_64
        command: bash -lc "apk add --no-cache linux-headers; make build fpm_alpine VERSION=$VERSION RELEASEVER=$RELEASEVER ALPINE_VERSION=$ALPINE_VERSION"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - ALPINE_VERSION=390
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
    alpine3.10:
        image: charlesportwoodii/alpine:3.10-build
        container_name: alpine36_x86_64
        command: bash -lc "apk add --no-cache linux-headers; make build fpm_alpine VERSION=$VERSION RELEASEVER=$RELEASEVER ALPINE_VERSION=$ALPINE_VERSION"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - ALPINE_VERSION=3100
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
