# docker-compose.yml

'1604': 
    build: .
    dockerfile: .docker/ubuntu_16.04
    command: bash -lc "make build VERISON=$VERSION RELEASEVER=$RELEASEVER && make fpm_debian VERSION=$VERSION"
    volumes: 
        - .:/data
    working_dir: /data
