# docker-compose.yml

version: '2'
services:

    trusty: 
        image: charlesportwoodii/trusty:build
        container_name: trusty_x64
        command: bash -lc "source .vs && make build VERISON=$VERSION RELEASEVER=$RELEASEVER && make fpm_debian VERSION=$VERSION"
        volumes: 
            - .:/data
        working_dir: /data

    xenial:
        image: charlesportwoodii/xenial:build
        container_name: xenial_x64
        command: bash -lc "source .vs && make build VERISON=$VERSION RELEASEVER=$RELEASEVER && make fpm_debian VERSION=$VERSION"
        volumes: 
            - .:/data
        working_dir: /data

    # This is the old package, we don't maintain it for RHEL7 or CentOS7