# docker-compose.yml

version: '3'
services:
    xenial:
        image: charlesportwoodii/ubuntu:16.04-build
        container_name: xenial_x64
        command: bash -lc "make build fpm_debian VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - EXTRA_DEB_PACKAGES=http://security.ubuntu.com/ubuntu/pool/universe/libz/libzip/libzip4_1.1.2-1.1_amd64.deb http://launchpadlibrarian.net/260671105/libzip-dev_1.1.2-1.1_amd64.deb
            - EXTRA_APT_PACKAGES=bison libbison-dev
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
            - BUILD_IMAGE=xenial
            - BUILD_OS=Ubuntu
            - BUILD_OS_VERSION=16.04
    bionic:
        image: charlesportwoodii/ubuntu:18.04-build
        container_name: xenial_x64
        command: bash -lc "make build fpm_debian VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
            - EXTRA_APT_PACKAGES=bison libbison-dev
            - BUILD_IMAGE=bionic
            - BUILD_OS=Ubuntu
            - BUILD_OS_VERSION=18.04
    focal:
        image: charlesportwoodii/ubuntu:20.04-build
        container_name: xenial_x64
        command: bash -lc "make build fpm_debian VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
            - EXTRA_APT_PACKAGES=bison libbison-dev
            - BUILD_IMAGE=focal
            - BUILD_OS=Ubuntu
            - BUILD_OS_VERSION=20.04
    centos7:
        image: charlesportwoodii/centos:7-build
        container_name: centos7_x86_64
        command: bash -lc "make build fpm_rpm VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - EXTRA_RPM_PACKAGES=http://rpms.remirepo.net/enterprise/7/remi/x86_64/libzip5-1.5.1-1.el7.remi.x86_64.rpm http://rpms.remirepo.net/enterprise/7/remi/x86_64//libzip5-devel-1.5.1-1.el7.remi.x86_64.rpm
            - REMOVE_RPM_PACKAGES=libzip libzip-devel
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
            - BUILD_IMAGE=centos7
            - BUILD_OS=CentOS
            - BUILD_OS_VERSION=7
    rhel7:
        image: charlesportwoodii/rhel:7-build
        container_name: rhel7_x86_64
        command: bash -lc "make build fpm_rpm VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - EXTRA_RPM_PACKAGES=http://rpms.remirepo.net/enterprise/7/remi/x86_64/libzip5-1.5.1-1.el7.remi.x86_64.rpm http://rpms.remirepo.net/enterprise/7/remi/x86_64//libzip5-devel-1.5.1-1.el7.remi.x86_64.rpm
            - REMOVE_RPM_PACKAGES=libzip libzip-devel
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
            - BUILD_IMAGE=rhel7
            - BUILD_OS=RHEL
            - BUILD_OS_VERSION=7
    alpine3.7:
        image: charlesportwoodii/alpine:3.7-build
        container_name: alpine37_x86_64
        command: bash -lc "apk add --no-cache linux-headers; make build fpm_alpine VERSION=$VERSION RELEASEVER=$RELEASEVER ALPINE_VERSION=$ALPINE_VERSION"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - ALPINE_VERSION=370
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
            - BUILD_IMAGE=alpine3.7
            - BUILD_OS=Alpine
            - BUILD_OS_VERSION=3.7
    alpine3.8:
        image: charlesportwoodii/alpine:3.8-build
        container_name: alpine38_x86_64
        command: bash -lc "apk add --no-cache linux-headers; make build fpm_alpine VERSION=$VERSION RELEASEVER=$RELEASEVER ALPINE_VERSION=$ALPINE_VERSION"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - ALPINE_VERSION=380
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
            - BUILD_IMAGE=alpine3.8
            - BUILD_OS=Alpine
            - BUILD_OS_VERSION=3.8
    alpine3.9:
        image: charlesportwoodii/alpine:3.9-build
        container_name: alpine38_x86_64
        command: bash -lc "apk add --no-cache linux-headers; make build fpm_alpine VERSION=$VERSION RELEASEVER=$RELEASEVER ALPINE_VERSION=$ALPINE_VERSION"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - ALPINE_VERSION=390
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
            - BUILD_IMAGE=alpine3.9
            - BUILD_OS=Alpine
            - BUILD_OS_VERSION=3.9
    alpine3.10:
        image: charlesportwoodii/alpine:3.10-build
        container_name: alpine310_x86_64
        command: bash -lc "apk add --no-cache linux-headers; make build fpm_alpine VERSION=$VERSION RELEASEVER=$RELEASEVER ALPINE_VERSION=$ALPINE_VERSION"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - ALPINE_VERSION=3100
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
            - BUILD_IMAGE=alpine3.10
            - BUILD_OS=Alpine
            - BUILD_OS_VERSION=3.10
    alpine3.11:
        image: charlesportwoodii/alpine:3.11-build
        container_name: alpine311_x86_64
        command: bash -lc "apk add --no-cache linux-headers; make build fpm_alpine VERSION=$VERSION RELEASEVER=$RELEASEVER ALPINE_VERSION=$ALPINE_VERSION"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
            - ALPINE_VERSION=3110
            - ENABLE_MAINTAINER_MODE=$ENABLE_MAINTAINER_MODE
            - BUILD_IMAGE=alpine3.11
            - BUILD_OS=Alpine
            - BUILD_OS_VERSION=3.11
