# docker-compose.yml

'1604': 
    build: .
    dockerfile: Dockerfile.ubuntu_16.04
    command: bash -lc 'source .vs && make build VERISON=$VERSION RELEASEVER=$RELEASEVER make fpm_debian VERSION=$VERSION && make pear VERISON=$VERSION'
    volumes: 
        - .:/data
    working_dir: /data