#!/bin/bash

set +e

if [ ! -f /etc/php/php.ini ]; then
	$(which cp) /etc/php/php.ini-production /etc/php/php.ini
	echo "date.timezone=UTC" >> /etc/php/php.ini
fi

if [ ! -f /etc/php/php-fpm.conf ]; then 
	$(which cp) /etc/php/php-fpm.conf.default /etc/php/php-fpm.conf
fi

$(which wget) http://pear.php.net/install-pear-nozlib.phar -O /tmp/pear.phar
$(which php) /tmp/pear.phar
$(which rm) -rf /tmp/pear.phar

$(which mkdir) -p /etc/php/conf.d

if [ -d /tmp/php-tmp/conf.d ]; then
	$(which cp) /tmp/php-tmp/conf.d/* /etc/php/conf.d/
	# Remove the old tmp directory to a separate directory so new builds don't interfere with it.
	$(which cp) -R /tmp/php-tmp /tmp/php-tmp-BAK
	$(which rm) -rf /tmp/php-tmp
fi

if [ ! -f /opt/openssl/ssl ]; then
	mkdir -p /opt/openssl
	ln -s /usr/lib/ssl /opt/openssl/ssl
fi

CODENAME=$(lsb_release --codename | cut -f2)
if [ $CODENAME = "xenial" ]
then
        systemctl enable php-fpm.service
        systemctl start php-fpm.service
else
	$(which update-rc.d) php-fpm defaults
	$(which service) php-fpm start
fi

exit 0
