#!/bin/bash
$(which make) install
# Copy the init.d file
cp init-php-fpm /etc/init.d/php-fpm
chmod a+x /etc/init.d/php-fpm

# Make the PHP directories
mkdir -p /etc/php/conf.d

# Copy the initial configs over
cp php.ini* /etc/php/
cp sapi/fpm/php-fpm.conf /etc/php/php-fpm.conf-default
