#!/bin/bash
$(which make) install
CODENAME=$(lsb_release --codename | cut -f2)
if [ $CODENAME = "xenial" ]
then
        cp php-fpm.service /lib/systemd/system/php-fpm.service
        systemctl enable php-fpm.service
else
	cp init-php-fpm /etc/init.d/php-fpm
	chmod a+x /etc/init.d/php-fpm
fi

# Make the PHP directories
mkdir -p /etc/php/conf.d

# Copy the initial configs over
cp php.ini* /etc/php/
cp php-fpm.conf /etc/php/php-fpm.conf-default
cp default.conf /etc/php/php-fpm-pool.conf-default
