#!/bin/bash

set +e
echo "Stopping PHP"

systemctl stop php-fpm.service
systemctl disable php-fpm.service

$(which touch) /var/run/php-fpm.pid

WWWDATAUSER=$(id www-data)
if [ $? -eq 1 ]; then
    echo "Creating www-data user"
    useradd -Mr www-data
fi

exit 0
