#!/bin/bash

set +e

VERSION=

if [ ! -d /etc/php/$VERSION ]; then
	$(which mkdir) -p /etc/php/$VERSION
	$(which cp) -R /usr/local/etc/php/$VERSION/* /etc/php/$VERSION
	$(which rm) /etc/php/$VERSION/LICENSE*
	$(which mv) /etc/php/$VERSION/php.ini-production /etc/php/$VERSION/php.ini
fi

$(which cp) -R /usr/local/etc/php/$VERSION/mods-available/* /etc/php/$VERSION/mods-available

$(which mkdir) -p /var/log/php/$VERSION/

if [ ! -f /etc/php/$VERSION/conf.d/openssl-default.ini ]; then
	OPENSSLDIR=$(openssl version -d | awk '{ print $2 }' | sed 's/"//g')
	echo "openssl.capath=$OPENSSLDIR/certs" > /etc/php/$VERSION/conf.d/openssl-default.ini 
fi

priority=$(echo $VERSION | tr -d '.')
update-alternatives --install /usr/bin/php php $(which php$VERSION) $priority

exit 0
