FROM ubuntu:14.04
ENV DEBIAN_FRONTEND noninteractive

# Install pre-dependencies
RUN apt-get update
RUN apt-get install wget m4 -y

# Install Postgresql
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

# Install build tools
RUN apt-get update
RUN apt-get install postgresql-contrib-9.5 postgresql-server-dev-9.5 make automake g++ autoconf checkinstall git build-essential libxml2-dev pkg-config libjpeg-turbo8-dev libpng12-dev libfreetype6-dev libicu-dev libmcrypt4 libmcrypt-dev libreadline6-dev libtool build-essential git ruby ruby-dev -y

# Install Bison
RUN wget http://launchpadlibrarian.net/140087283/libbison-dev_2.7.1.dfsg-1_amd64.deb
RUN wget http://launchpadlibrarian.net/140087282/bison_2.7.1.dfsg-1_amd64.deb
RUN dpkg -i libbison-dev_2.7.1.dfsg-1_amd64.deb
RUN dpkg -i bison_2.7.1.dfsg-1_amd64.deb

# Install FPM
RUN gem install fpm
