#!/bin/bash

set +e

VERSION=

if [ ! -d /etc/php/$VERSION ]; then
	$(which mkdir) -p /etc/php/$VERSION
	$(which cp) -R /usr/local/etc/php/$VERSION/* /etc/php/$VERSION
	$(which rm) /etc/php/$VERSION/LICENSE*
	$(which mv) /etc/php/$VERSION/php.ini-production /etc/php/$VERSION/php.ini
	$(which mv) /etc/php/$VERSION/php-fpm.conf.default /etc/php/$VERSION/php-fpm.conf
	$(which mv) /etc/php/$VERSION/php-fpm.d/pool.conf.default /etc/php/$VERSION/php-fpm.d/pool.conf
fi

if [ ! -f /var/log/php/$VERSION/ ]; then
	$(which mkdir) -p /var/log/php/$VERSION/
	$(which touch) /var/log/php/$VERSION/slow.log
	$(which chmod) -R 754 /var/log/php/$VERSION/slow.log
fi

$(which mkdir) -p /var/run/php/$VERSION

if [ ! -f /etc/php/$VERSION/conf.d/openssl-default.ini ]; then
	OPENSSLDIR=$(openssl version -d | awk '{ print $2 }' | sed 's/"//g')
	echo "openssl.capath=$OPENSSLDIR/certs" > /etc/php/$VERSION/conf.d/openssl-default.ini 
fi

which systemctl
if [ "$?" == 1 ]
then
	$(which cp) /usr/local/etc/init.d/php-fpm-$VERSION /etc/init.d/php-fpm-$VERSION

	$(which update-rc.d) php-fpm-$VERSION defaults
	$(which service) php-fpm-$VERSION start
else
	$(which systemctl) enable php-fpm-$VERSION.service
	$(which systemctl) start php-fpm-$VERSION.service
fi

update-alternatives --install /usr/bin/php php $(which php$VERSION) 1
exit 0