#!/bin/bash

set +e

if [ ! -d /etc/php ]; then
	$(which mkdir) -p /etc/php
	$(which cp) -R /usr/local/etc/php/* /etc/php
	$(which mv) /etc/php/php.ini-production /etc/php/php.ini
	$(which mv) /etc/php/php-fpm.conf.default /etc/php/php-fpm.conf
	$(which mv) /etc/php/php-fpm.d/pool.conf.default /etc/php/php-fpm.d/pool.conf
fi

if [ ! -f /var/log/php ]; then
	$(which mkdir) -p /var/log/php
	$(which touch) /var/log/php/slow.log
	$(which chmod) -R 754 /var/log/php/slow.log
fi

if [ ! -f /etc/php/conf.d/openssl-default.ini ]; then
	OPENSSLDIR=$(openssl version -d | awk '{ print $2 }' | sed 's/"//g')
	echo "openssl.capath=$OPENSSLDIR/certs" > /etc/php/conf.d/openssl-default.ini 
fi

which lsb_release
if [ "$?" == 0 ]
then
        CODENAME=$(lsb_release --codename | cut -f2)
        if [ "$CODENAME" = "precise" ]
        then
			if [ ! -f /etc/init.d/php-fpm ]; then
				$(which cp) /usr/local/etc/init.d/php-fpm /etc/init.d/php-fpm
			fi

            $(which update-rc.d) php-fpm defaults
			$(which service) php-fpm start
        else
            systemctl enable php-fpm.service
        	systemctl start php-fpm.service
        fi
else
        systemctl enable php-fpm.service
        systemctl start php-fpm.service
fi

exit 0
