#!/bin/bash

set +e
echo "Stopping PHP and Backing Up conf.d"
CODENAME=$(lsb_release --codename | cut -f2)


which lsb_release
if [ "$?" == 0 ]
then
        CODENAME=$(lsb_release --codename | cut -f2)
        if [ "$CODENAME" = "precise" ]
        then
                $(which service) php-fpm stop
        else
                systemctl stop php-fpm.service
                systemctl disable php-fpm.service
        fi
else
        systemctl stop php-fpm.service
        systemctl disable php-fpm.service
fi

if [ -d /tmp/php-tmp/conf.d ]; then
	$(which cp) -R /etc/php/conf.d/* /tmp/php-tmp/conf.d/
fi

$(which touch) /var/run/php-fpm.pid
exit 0
