#!/bin/bash

set +e
echo "Stopping PHP"

which systemctl
if [ "$?" == 1 ]
then
    $(which service) php-fpm stop
else
    $(which systemctl) stop php-fpm.service
    $(which systemctl) disable php-fpm.service
fi

$(which touch) /var/run/php-fpm.pid
exit 0
