#!/bin/bash

set +e

which systemctl
if [ "$?" == 1 ]
then
    $(which service) php-fpm stop
else
    $(which systemctl) stop php-fpm.service
    $(which systemctl) disable php-fpm.service
fi

exit 0
