#!/bin/bash

set +e

which lsb_release
if [ "$?" == 0 ]
then
        CODENAME=$(lsb_release --codename | cut -f2)
        if [ "$CODENAME" = "precise" ]
        then
                $(which service) php-fpm stop
        else
                systemctl stop php-fpm.service
                systemctl disable php-fpm.service
                rm -rf /lib/systemd/system/php-fpm.service
        fi
else
        systemctl stop php-fpm.service
        systemctl disable php-fpm.service
        rm -rf /lib/systemd/system/php-fpm.service
fi

exit 0
