#!/bin/bash
$(which make) install

which lsb_release
if [ "$?" == 0 ]
then
        CODENAME=$(lsb_release --codename | cut -f2)
        if [ "$CODENAME" = "precise" ]
        then
                cp init-php-fpm /etc/init.d/php-fpm
	        chmod a+x /etc/init.d/php-fpm
        else
                cp php-fpm.service /lib/systemd/system/php-fpm.service
                systemctl enable php-fpm.service
        fi
else
        cp php-fpm.service /lib/systemd/system/php-fpm.service
        systemctl enable php-fpm.service
fi

# Make the PHP directories
mkdir -p /etc/php/conf.d

# Copy the initial configs over
cp php.ini* /etc/php/
cp php-fpm.conf.default /etc/php/php-fpm.conf-default
cp pool.conf.default /etc/php/php-fpm-pool.conf-default
