#!/bin/bash

set +e

VERSION=

if [ ! -f /etc/php/$VERSION/php.ini ]; then
	$(which mkdir) -p /etc/php/$VERSION/conf.d
	$(which cp) -R /usr/local/etc/php/$VERSION/* /etc/php/$VERSION
	$(which rm) /etc/php/$VERSION/LICENSE*
	$(which mv) /etc/php/$VERSION/php.ini-production /etc/php/$VERSION/php.ini
fi

$(which cp) -R /usr/local/etc/php/$VERSION/mods-available/* /etc/php/$VERSION/mods-available

OPENSSLDIR=$(openssl version -d | awk '{ print $2 }' | sed 's/"//g')
echo "openssl.capath=$OPENSSLDIR/certs" > /etc/php/$VERSION/conf.d/openssl-default.ini 

exit 0
