#!/bin/bash

set +e

VERSION=

if [ ! -f /etc/php/$VERSION/php-fpm.conf ]; then
	$(which mv) /etc/php/$VERSION/php-fpm.conf.default /etc/php/$VERSION/php-fpm.conf
	$(which mv) /etc/php/$VERSION/php-fpm.d/pool.conf.default /etc/php/$VERSION/php-fpm.d/pool.conf
fi

if [ ! -f /var/log/php/$VERSION/ ]; then
	$(which mkdir) -p /var/log/php/$VERSION/
	$(which touch) /var/log/php/$VERSION/slow.log
	$(which chmod) -R 754 /var/log/php/$VERSION/slow.log
fi

$(which mkdir) -p /var/run/php/$VERSION

rc-update add php-fpm-$VERSION default
rc-update php-fpm-$VERSION start

exit 0